feat: Create an OAuth2 module for authenticating users
rivet-gg/opengb-modules pull request #86
Opened 2024-05-10 12:18 UTC by Blckbrry-Pi

2024-05-10 12:18 UTC, Blckbrry-Pi commented
* **#86** <a href="https://app.graphite.dev/github/pr/rivet-gg/opengb-registry/86?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @Blckbrry-Pi and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-05-29 19:30 UTC, MasterPtato commented on modules/auth_oauth2/utils/client.ts
> +	const redirectUri = new URL(`./modules/auth_oauth2/route/callback/${provider}`, uri.origin).toString();
didn't know you could do `./` with `URL`, neat

2024-05-29 19:30 UTC, MasterPtato approved these changes

2024-06-04 03:26 UTC, NathanFlurry requested changes
see notion

2024-07-01 23:57 UTC, Blckbrry-Pi commented on modules/auth_oauth2/routes/login_callback.ts
> +	let tokens: Awaited<ReturnType<typeof client.code.getToken>>;
Yes, but it would require modifying `tokens`. Will do now.

2024-07-02 00:24 UTC, Blckbrry-Pi commented on modules/auth_oauth2/routes/login_callback.ts
> +	let tokens: Awaited<ReturnType<typeof client.code.getToken>>;
I was mistaken, I forgot which `Tokens` it was.

2024-07-10 19:40 UTC, Blckbrry-Pi commented on modules/auth_oauth2/routes/login_callback.ts
> +	const user = await ctx.db.oAuthUsers.findFirst({
OAuth2 impl changed, no longer relevant

2024-08-02 02:22 UTC, closed without merging